[package]
name = "rust_lib_my_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
irondash_texture = { version = "0.5.0" }
irondash_run_loop = { version = "0.5.0" }
irondash_dart_ffi = "0.2.0"
simple_logger = "2.1"
log = "0.4"
anyhow = "1.0.81"
async-trait = "0.1.77"
tokio = { version = "1", features = ["full"] }
flume = "0.11.1"
simple-log = "2.1.1"
irondash_engine_context = "0.5.0"
image = "0.25.5"
lazy_static = "1.5.0"
glib-sys = "0.18.1"
gobject-sys = "0.18.0"
gdk-sys = "0.18.0"
gtk-sys = "0.18.0"
gl_loader = "0.1.2"
glow = { version = "0.12.3", features = [] }